### ISSUE TITLE
unexpected origin response: 401 Unauthorized

### ISSUE THREAD

**Issue by Drazzilb08** [aeleos/cloudflared#10]
So I'm running two instances of Cloudflared one for each of my domains.
My primary domain is up and running with out any issues.
However my secondary domain has 
`unexpected origin response: 401 Unauthorized` 
show up over and over w/in the logs. 
The thing is when I go to the grafana.domain.com everything is up and running. 

I tried my best to configure both exactly the same (minus tunnel information)

I'm not mad that its working, just would like to know if this error poses a security concern.

**Comment by aeleos** [comment]
Is your grafana instance sitting at the root of the domain? If so it’s probably just a bot probing your domain and grafana returns 491 because they aren’t logged in. If that’s the case it shouldn’t be a security issue. I would recommend putting it behind a reverse proxy that has a username and password, as a vulnerability with grafana could cause an issue if it’s exposed completely
