### ISSUE TITLE
no ID supplied during tunnel creation

### ISSUE THREAD

**Issue by kevinmarchese** [aeleos/cloudflared#13]
Hi, 

when I authorize a domain in Cloudflare I then create the tunnel however the tunnel ID never prints in the terminal. likewise the .json file created that holds the secret also isn't named. it shows up in ls as .json with no name or in this case the ID. Than you for any help/hints etc. I would love to get this up and running of course the ID is critical. I also followed up with IBRACORP's video saying this is odd. 

![Screen Shot 2021-07-25 at 8 59 28 PM](https://user-images.githubusercontent.com/9823256/126919838-5c1548aa-0d8e-4007-a773-5cf64cb6ba34.png)
also the list command retunrs 
Error listing tunnels: failed to decode response: json: cannot unmarshal object into Go value of type []tunnelstore.Tunnel

**Comment by kevinmarchese** [comment]
you have to set a specific version to get an ID docker run -it --rm -v /mnt/user/appdata/cloudflared:/home/nonroot/.cloudflared/ cloudflare/cloudflared**:2021.6.0** tunnel

**Comment by bigmak40** [comment]
I ran into this issue today; I used 2021.8.1 successfully. It seems like this is something that needs to be fixed; a couple ways to do this.

1. Update the README.md to state that a version must be included
2. Have cloudflared work with no version specified
3. Have cloudflared say "version must be specified" rather than a vague answer

**Comment by aeleos** [comment]
@bigmak40 @kevinmarchese Sorry I didn't see these, points 2 and 3 won't work since I don't control the actual cloudflared docker repo. I will add this to the troubleshooting section.
