### ISSUE TITLE
using cloudflared only with sub domains

### ISSUE THREAD

**Issue by Goldmaster** [aeleos/cloudflared#15]
Hi there I have been following ibracorp video on using Argo. However, I want to keep my main WordPress website and set argo to only tunnel with sub domains. What are the correct settings for the cloudflare dns records? I have got the docker working fine it seams. Do I need to make any edits to the config file?

**Comment by aeleos** [comment]
You shouldn't need to make any edits to the config file. In DNS, instead of following the video where it points the root domain to the tunnel, and then each subdomain points to the root domain, you want to keep your root domain pointing to your wordpress site, and then have each subdomain point to the tunnel individually.

You could also run a wordpress site behind your tunnel on whatever server you are using, and then use the reverse proxy point the root to your internal wordpress site, but that requires more setup than having a cloud based wordpress site.
